version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hikmetinizinde-web
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - web_network

  nginx:
    image: nginx:alpine
    container_name: hikmetinizinde-nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./build:/usr/share/nginx/html
    ports:
      - "8080:80"   # HTTP için 8080 portu
      - "8443:443"  # HTTPS için 8443 portu
    depends_on:
      - web
    networks:
      - web_network

networks:
  web_network:
    driver: bridge