version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hikmetinizinde-web
    ports:
      - "8080:80"
    networks:
      - web_network

networks:
  web_network:
    driver: bridge